<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66a92b76506ef',
	'title' => 'Scholar Fields',
	'fields' => array(
		array(
			'key' => 'field_66a92b7792555',
			'label' => 'First Name',
			'name' => 'first_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a92b94c5f85',
			'label' => 'Last Name',
			'name' => 'last_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a92ba2c5f86',
			'label' => 'Email',
			'name' => 'email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a92babc5f87',
			'label' => 'Job Title',
			'name' => 'job_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a92c65c1201',
			'label' => 'Areas of Scholarship',
			'name' => 'areas_of_scholarship',
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Aging' => 'Aging',
				'Arts' => 'Arts',
				'Civics, Democracy, and Political Involvement' => 'Civics, Democracy, and Political Involvement',
				'Commercialization and Industry Development' => 'Commercialization and Industry Development',
				'Criminal Justice' => 'Criminal Justice',
				'Early Childhood' => 'Early Childhood',
				'Economic Development' => 'Economic Development',
				'Entrepreneurship' => 'Entrepreneurship',
				'Environment, Environmental Justice, and Sustainability' => 'Environment, Environmental Justice, and Sustainability',
				'Equity, Diversity, and Inclusion' => 'Equity, Diversity, and Inclusion',
				'Food' => 'Food',
				'Gender and Sexuality' => 'Gender and Sexuality',
				'Health' => 'Health',
				'Housing' => 'Housing',
				'Immigration' => 'Immigration',
				'Internationalization and Globalization' => 'Internationalization and Globalization',
				'K-12 Education, Student Achievement, and College Access' => 'K-12 Education, Student Achievement, and College Access',
				'Leadership' => 'Leadership',
				'Neighborhood Development and City Planning' => 'Neighborhood Development and City Planning',
				'Poverty and Homelessness' => 'Poverty and Homelessness',
				'Rural Development' => 'Rural Development',
				'Social and Historic Injustice' => 'Social and Historic Injustice',
				'Technology and Tech Transfer' => 'Technology and Tech Transfer',
				'Transportation' => 'Transportation',
				'Veterinary and Animal Welfare' => 'Veterinary and Animal Welfare',
				'Youth and Families' => 'Youth and Families',
				'Other' => 'Other',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'allow_custom' => 0,
			'layout' => 'vertical',
			'toggle' => 0,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Add new choice',
		),
		array(
			'key' => 'field_66a92d1d05b7a',
			'label' => 'Campus',
			'name' => 'campus',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'UConn Main Campus - Storrs' => 'UConn Main Campus - Storrs',
				'UConn Health - Farmington' => 'UConn Health - Farmington',
				'UConn Avery Point' => 'UConn Avery Point',
				'UConn Hartford' => 'UConn Hartford',
				'UConn Law' => 'UConn Law',
				'UConn Stamford' => 'UConn Stamford',
				'UConn Waterbury' => 'UConn Waterbury',
				'UConn Extension' => 'UConn Extension',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_66a92e364f8a0',
			'label' => 'School/College',
			'name' => 'schoolcollege',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'College of Agriculture, Health and Natural Resources' => 'College of Agriculture, Health and Natural Resources',
				'College of Engineering' => 'College of Engineering',
				'College of Liberal Arts & Sciences' => 'College of Liberal Arts & Sciences',
				'Neag School of Education' => 'Neag School of Education',
				'School of Business' => 'School of Business',
				'School of Dental Medicine' => 'School of Dental Medicine',
				'School of Fine Arts' => 'School of Fine Arts',
				'School of Law' => 'School of Law',
				'School of Medicine' => 'School of Medicine',
				'School of Nursing' => 'School of Nursing',
				'School of Pharmacy' => 'School of Pharmacy',
				'School of Social Work' => 'School of Social Work',
				'The Graduate School' => 'The Graduate School',
				'UConn Library' => 'UConn Library',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'oe_scholar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

add_action( 'init', function() {
	register_post_type( 'oe_scholar', array(
	'labels' => array(
		'name' => 'OE Scholars',
		'singular_name' => 'OE Scholar',
		'menu_name' => 'O&E Scholars',
		'all_items' => 'All O&E Scholars',
		'edit_item' => 'Edit O&E Scholar',
		'view_item' => 'View O&E Scholar',
		'view_items' => 'View O&E Scholars',
		'add_new_item' => 'Add New O&E Scholar',
		'add_new' => 'Add New O&E Scholar',
		'new_item' => 'New O&E Scholar',
		'parent_item_colon' => 'Parent O&E Scholar:',
		'search_items' => 'Search O&E Scholars',
		'not_found' => 'No o&e scholars found',
		'not_found_in_trash' => 'No o&e scholars found in Trash',
		'archives' => 'O&E Scholar Archives',
		'attributes' => 'O&E Scholar Attributes',
		'insert_into_item' => 'Insert into o&e scholar',
		'uploaded_to_this_item' => 'Uploaded to this o&e scholar',
		'filter_items_list' => 'Filter o&e scholars list',
		'filter_by_date' => 'Filter o&e scholars by date',
		'items_list_navigation' => 'O&E Scholars list navigation',
		'items_list' => 'O&E Scholars list',
		'item_published' => 'O&E Scholar published.',
		'item_published_privately' => 'O&E Scholar published privately.',
		'item_reverted_to_draft' => 'O&E Scholar reverted to draft.',
		'item_scheduled' => 'O&E Scholar scheduled.',
		'item_updated' => 'O&E Scholar updated.',
		'item_link' => 'O&E Scholar Link',
		'item_link_description' => 'A link to a o&e scholar.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'has_archive' => 'scholars-directory',
	'rewrite' => array(
		'feeds' => false,
	),
	'delete_with_user' => false,
) );
} );

